CREATE TABLE dtb_payment (
    payment_id int NOT NULL,
    payment_method nvarchar(max),
    charge numeric(9),
    rule_max numeric(9),
    rank int,
    note nvarchar(max),
    fix smallint,
    status smallint NOT NULL DEFAULT 1,
    del_flg smallint NOT NULL DEFAULT 0,
    creator_id int NOT NULL,
    create_date datetimeoffset NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date datetimeoffset NOT NULL,
    payment_image nvarchar(max),
    upper_rule numeric(9),
    charge_flg smallint DEFAULT 1,
    rule_min numeric(9),
    upper_rule_max numeric(9),
    module_id int,
    module_path nvarchar(max),
    memo01 nvarchar(max),
    memo02 nvarchar(max),
    memo03 nvarchar(max),
    memo04 nvarchar(max),
    memo05 nvarchar(max),
    memo06 nvarchar(max),
    memo07 nvarchar(max),
    memo08 nvarchar(max),
    memo09 nvarchar(max),
    memo10 nvarchar(max),
    PRIMARY KEY (payment_id)
);