CREATE TABLE dtb_products (
    product_id int NOT NULL,
    name nvarchar(max) NOT NULL,
    maker_id int,
    status smallint NOT NULL DEFAULT 2,
    comment1 nvarchar(max),
    comment2 nvarchar(max),
    comment3 nvarchar(max),
    comment4 nvarchar(max),
    comment5 nvarchar(max),
    comment6 nvarchar(max),
    note nvarchar(max),
    main_list_comment nvarchar(max),
    main_list_image nvarchar(max),
    main_comment nvarchar(max),
    main_image nvarchar(max),
    main_large_image nvarchar(max),
    sub_title1 nvarchar(max),
    sub_comment1 nvarchar(max),
    sub_image1 nvarchar(max),
    sub_large_image1 nvarchar(max),
    sub_title2 nvarchar(max),
    sub_comment2 nvarchar(max),
    sub_image2 nvarchar(max),
    sub_large_image2 nvarchar(max),
    sub_title3 nvarchar(max),
    sub_comment3 nvarchar(max),
    sub_image3 nvarchar(max),
    sub_large_image3 nvarchar(max),
    sub_title4 nvarchar(max),
    sub_comment4 nvarchar(max),
    sub_image4 nvarchar(max),
    sub_large_image4 nvarchar(max),
    sub_title5 nvarchar(max),
    sub_comment5 nvarchar(max),
    sub_image5 nvarchar(max),
    sub_large_image5 nvarchar(max),
    sub_title6 nvarchar(max),
    sub_comment6 nvarchar(max),
    sub_image6 nvarchar(max),
    sub_large_image6 nvarchar(max),
    del_flg smallint NOT NULL DEFAULT 0,
    creator_id int NOT NULL,
    create_date datetimeoffset NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date datetimeoffset NOT NULL,
    deliv_date_id int,
    PRIMARY KEY (product_id)
);