CREATE TABLE [dbo].[dtb_payment] (
    [payment_id]     INT                NOT NULL,
    [payment_method] NVARCHAR (MAX)     NULL,
    [charge]         NUMERIC (9)        NULL,
    [rule_max]       NUMERIC (9)        NULL,
    [rank]           INT                NULL,
    [note]           NVARCHAR (MAX)     NULL,
    [fix]            SMALLINT           NULL,
    [status]         SMALLINT           DEFAULT ((1)) NOT NULL,
    [del_flg]        SMALLINT           DEFAULT ((0)) NOT NULL,
    [creator_id]     INT                NOT NULL,
    [create_date]    DATETIMEOFFSET (7) DEFAULT (getdate()) NOT NULL,
    [update_date]    DATETIMEOFFSET (7) NOT NULL,
    [payment_image]  NVARCHAR (MAX)     NULL,
    [upper_rule]     NUMERIC (9)        NULL,
    [charge_flg]     SMALLINT           DEFAULT ((1)) NULL,
    [rule_min]       NUMERIC (9)        NULL,
    [upper_rule_max] NUMERIC (9)        NULL,
    [module_id]      INT                NULL,
    [module_path]    NVARCHAR (MAX)     NULL,
    [memo01]         NVARCHAR (MAX)     NULL,
    [memo02]         NVARCHAR (MAX)     NULL,
    [memo03]         NVARCHAR (MAX)     NULL,
    [memo04]         NVARCHAR (MAX)     NULL,
    [memo05]         NVARCHAR (MAX)     NULL,
    [memo06]         NVARCHAR (MAX)     NULL,
    [memo07]         NVARCHAR (MAX)     NULL,
    [memo08]         NVARCHAR (MAX)     NULL,
    [memo09]         NVARCHAR (MAX)     NULL,
    [memo10]         NVARCHAR (MAX)     NULL,
    PRIMARY KEY CLUSTERED ([payment_id] ASC)
);

