CREATE TABLE [dbo].[dtb_order] (
    [order_id]           INT                NOT NULL,
    [order_temp_id]      NVARCHAR (MAX)     NULL,
    [customer_id]        INT                NOT NULL,
    [message]            NVARCHAR (MAX)     NULL,
    [order_name01]       NVARCHAR (MAX)     NULL,
    [order_name02]       NVARCHAR (MAX)     NULL,
    [order_kana01]       NVARCHAR (MAX)     NULL,
    [order_kana02]       NVARCHAR (MAX)     NULL,
    [order_company_name] NVARCHAR (MAX)     NULL,
    [order_email]        NVARCHAR (MAX)     NULL,
    [order_tel01]        NVARCHAR (MAX)     NULL,
    [order_tel02]        NVARCHAR (MAX)     NULL,
    [order_tel03]        NVARCHAR (MAX)     NULL,
    [order_fax01]        NVARCHAR (MAX)     NULL,
    [order_fax02]        NVARCHAR (MAX)     NULL,
    [order_fax03]        NVARCHAR (MAX)     NULL,
    [order_zip01]        NVARCHAR (MAX)     NULL,
    [order_zip02]        NVARCHAR (MAX)     NULL,
    [order_zipcode]      NVARCHAR (MAX)     NULL,
    [order_country_id]   INT                NULL,
    [order_pref]         SMALLINT           NULL,
    [order_addr01]       NVARCHAR (MAX)     NULL,
    [order_addr02]       NVARCHAR (MAX)     NULL,
    [order_sex]          SMALLINT           NULL,
    [order_birth]        DATETIMEOFFSET (7) NULL,
    [order_job]          INT                NULL,
    [subtotal]           NUMERIC (9)        NULL,
    [discount]           NUMERIC (9)        DEFAULT ((0)) NOT NULL,
    [deliv_id]           INT                NULL,
    [deliv_fee]          NUMERIC (9)        NULL,
    [charge]             NUMERIC (9)        NULL,
    [use_point]          NUMERIC (9)        DEFAULT ((0)) NOT NULL,
    [add_point]          NUMERIC (9)        DEFAULT ((0)) NOT NULL,
    [birth_point]        NUMERIC (9)        DEFAULT ((0)) NOT NULL,
    [tax]                NUMERIC (9)        NULL,
    [total]              NUMERIC (9)        NULL,
    [payment_total]      NUMERIC (9)        NULL,
    [payment_id]         INT                NULL,
    [payment_method]     NVARCHAR (MAX)     NULL,
    [note]               NVARCHAR (MAX)     NULL,
    [status]             SMALLINT           NULL,
    [create_date]        DATETIMEOFFSET (7) DEFAULT (getdate()) NOT NULL,
    [update_date]        DATETIMEOFFSET (7) NOT NULL,
    [commit_date]        DATETIMEOFFSET (7) NULL,
    [payment_date]       DATETIMEOFFSET (7) NULL,
    [device_type_id]     INT                NULL,
    [del_flg]            SMALLINT           DEFAULT ((0)) NOT NULL,
    [memo01]             NVARCHAR (MAX)     NULL,
    [memo02]             NVARCHAR (MAX)     NULL,
    [memo03]             NVARCHAR (MAX)     NULL,
    [memo04]             NVARCHAR (MAX)     NULL,
    [memo05]             NVARCHAR (MAX)     NULL,
    [memo06]             NVARCHAR (MAX)     NULL,
    [memo07]             NVARCHAR (MAX)     NULL,
    [memo08]             NVARCHAR (MAX)     NULL,
    [memo09]             NVARCHAR (MAX)     NULL,
    [memo10]             NVARCHAR (MAX)     NULL,
    PRIMARY KEY CLUSTERED ([order_id] ASC),
    CONSTRAINT [FK_dtb_order_dtb_payment] FOREIGN KEY ([payment_id]) REFERENCES [dbo].[dtb_payment] ([payment_id])
);


GO
ALTER TABLE [dbo].[dtb_order] NOCHECK CONSTRAINT [FK_dtb_order_dtb_payment];

