CREATE TABLE dtb_order (
    order_id int NOT NULL,
    order_temp_id nvarchar(max),
    customer_id int NOT NULL,
    message nvarchar(max),
    order_name01 nvarchar(max),
    order_name02 nvarchar(max),
    order_kana01 nvarchar(max),
    order_kana02 nvarchar(max),
    order_company_name nvarchar(max),
    order_email nvarchar(max),
    order_tel01 nvarchar(max),
    order_tel02 nvarchar(max),
    order_tel03 nvarchar(max),
    order_fax01 nvarchar(max),
    order_fax02 nvarchar(max),
    order_fax03 nvarchar(max),
    order_zip01 nvarchar(max),
    order_zip02 nvarchar(max),
    order_zipcode nvarchar(max),
    order_country_id int,
    order_pref smallint,
    order_addr01 nvarchar(max),
    order_addr02 nvarchar(max),
    order_sex smallint,
    order_birth datetimeoffset,
    order_job int,
    subtotal numeric(9),
    discount numeric(9) NOT NULL DEFAULT 0,
    deliv_id int,
    deliv_fee numeric(9),
    charge numeric(9),
    use_point numeric(9) NOT NULL DEFAULT 0,
    add_point numeric(9) NOT NULL DEFAULT 0,
    birth_point numeric(9) NOT NULL DEFAULT 0,
    tax numeric(9),
    total numeric(9),
    payment_total numeric(9),
    payment_id int,
    payment_method nvarchar(max),
    note nvarchar(max),
    status smallint,
    create_date datetimeoffset NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date datetimeoffset NOT NULL,
    commit_date datetimeoffset,
    payment_date datetimeoffset,
    device_type_id int,
    del_flg smallint NOT NULL DEFAULT 0,
    memo01 nvarchar(max),
    memo02 nvarchar(max),
    memo03 nvarchar(max),
    memo04 nvarchar(max),
    memo05 nvarchar(max),
    memo06 nvarchar(max),
    memo07 nvarchar(max),
    memo08 nvarchar(max),
    memo09 nvarchar(max),
    memo10 nvarchar(max),
    PRIMARY KEY (order_id)
);