CREATE TABLE dtb_shipping (
    shipping_id int NOT NULL,
    order_id int NOT NULL,
    shipping_name01 nvarchar(max),
    shipping_name02 nvarchar(max),
    shipping_kana01 nvarchar(max),
    shipping_kana02 nvarchar(max),
    shipping_company_name nvarchar(max),
    shipping_tel01 nvarchar(max),
    shipping_tel02 nvarchar(max),
    shipping_tel03 nvarchar(max),
    shipping_fax01 nvarchar(max),
    shipping_fax02 nvarchar(max),
    shipping_fax03 nvarchar(max),
    shipping_country_id int,
    shipping_pref smallint,
    shipping_zip01 nvarchar(max),
    shipping_zip02 nvarchar(max),
    shipping_zipcode nvarchar(max),
    shipping_addr01 nvarchar(max),
    shipping_addr02 nvarchar(max),
    time_id int,
    shipping_time nvarchar(max),
    shipping_num nvarchar(max),
    shipping_date datetimeoffset,
    shipping_commit_date datetimeoffset,
    rank int,
    create_date datetimeoffset NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date datetimeoffset NOT NULL,
    del_flg smallint NOT NULL DEFAULT 0,
    PRIMARY KEY (shipping_id, order_id)
);